architect_task:
  description: >
    Create a basic plan for building a simple MVP version of a {project}.
    Focus on the core features, basic file structure, and tech stack.
    Make the structure minimal but enough to get a working demo.
  expected_output: >
    A simple architectural overview with:
    - Project goals
    - Key components or files
    - Basic data flow or structure
  agent: architect
  output_file: architecture.md

coder_task:
  description: >
    Based on the architect's plan, implement the core parts of the {project} MVP.
    Keep it lean and functional. Use the FileWriter tool to save all your code files.
    If you need to simulate behavior (e.g. without a real interpreter), do so with clear comments or mocked logic.
  expected_output: >
    Working code files saved using the FileWriter tool that implement the key features defined in the plan.
    Code should be readable and logically structured.
  agent: coder
  context:
    - architect_task

review_task:
  description: >
    Review the code files created for the {project} MVP. Read each file using the FileRead tool.
    Suggest improvements using diffs. Do not modify the original code files directly.
    Instead, save all your suggested diffs into a markdown file using the FileWriter tool.
  expected_output: >
    A markdown file containing diff-style suggestions for each file reviewed.
  agent: reviewer
  context:
    - coder_task
  output_file: code_review_diffs.md
